site_name: CUC ACM-Wiki

# Contents
nav:
  - 首页:
      - 关于本项目: index.md
      - F.A.Q: FAQ.md
  - 2020春集训安排:
      - 课程安排: 2020Spring.md  
  - C语言基础:
      - 基本语法: c-basic/grammar.md
      - 逻辑结构: c-basic/structure.md
      - 数组: c-basic/array.md
      - 函数: c-basic/function.md
  - STL:
      - STL简介: STL/introduction.md
      - Vector: STL/vector.md
      - Map: STL/map.md
      - Set: STL/set.md
      - Queue: STL/queue.md
      - List: STL/list.md
      - Bitset: STL/bitset.md

  
## Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''

extra_javascript:
  - '_static/js/extra.js?v=16'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css?v=12'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde